// Code generated by mockery v1.0.0
package mocks

import http "net/http"
import mock "github.com/stretchr/testify/mock"

// URLParamReader is an autogenerated mock type for the URLParamReader type
type URLParamReader struct {
	mock.Mock
}

// Read provides a mock function with given fields: r, name
func (_m *URLParamReader) Read(r *http.Request, name string) string {
	ret := _m.Called(r, name)

	var r0 string
	if rf, ok := ret.Get(0).(func(*http.Request, string) string); ok {
		r0 = rf(r, name)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
